name: CI

on: [push]

jobs:
  build-test:
    name: PHPUnit tests
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        version: ['8.0', '8.2', '8.3', '8.4']

    steps:
    - uses: actions/checkout@v3
    - name: Set up PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: ${{ matrix.version }}
        tools: composer:v2
    - name: Composer install
      run: composer install
    - name: Run PHP Unit tests
      shell: bash
      run: vendor/bin/phpunit --coverage-text
